// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfBRCyHxjAaGh_NIN0qy5FLnYQf5ua1PY',
    appId: '1:471270629661:web:1040f73adc53a383f5c1f4',
    messagingSenderId: '471270629661',
    projectId: 'ibs-platform-7348a',
    authDomain: 'ibs-platform-7348a.firebaseapp.com',
    storageBucket: 'ibs-platform-7348a.firebasestorage.app',
    measurementId: 'G-CSY6FPDBVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiI5Sd-nLNdOc-yOHi639OsQfnj41YGpk',
    appId: '1:471270629661:android:ffa1db1f6f86dd0af5c1f4',
    messagingSenderId: '471270629661',
    projectId: 'ibs-platform-7348a',
    storageBucket: 'ibs-platform-7348a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSVas28sgusSJqPhb-PI-eblVM-bcd6c',
    appId: '1:471270629661:ios:a1acda98c76398cdf5c1f4',
    messagingSenderId: '471270629661',
    projectId: 'ibs-platform-7348a',
    storageBucket: 'ibs-platform-7348a.firebasestorage.app',
    iosClientId: '471270629661-9mkm62erk778jm8fa7budkvc75sp5ije.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibsPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdSVas28sgusSJqPhb-PI-eblVM-bcd6c',
    appId: '1:471270629661:ios:a1acda98c76398cdf5c1f4',
    messagingSenderId: '471270629661',
    projectId: 'ibs-platform-7348a',
    storageBucket: 'ibs-platform-7348a.firebasestorage.app',
    iosClientId: '471270629661-9mkm62erk778jm8fa7budkvc75sp5ije.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibsPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfBRCyHxjAaGh_NIN0qy5FLnYQf5ua1PY',
    appId: '1:471270629661:web:e2b6c8d557e17e16f5c1f4',
    messagingSenderId: '471270629661',
    projectId: 'ibs-platform-7348a',
    authDomain: 'ibs-platform-7348a.firebaseapp.com',
    storageBucket: 'ibs-platform-7348a.firebasestorage.app',
    measurementId: 'G-ZH4BW2SCBG',
  );
}
